### ISSUE TITLE
Linker command failed on example app

### ISSUE THREAD

**Issue by kadze** [VoIPGRID/VialerSIPLib#127]
### Version

3.3.1

### Expected behaviour

success build

### Actual behaviour

build failed

### Stacktrace / Error message

Ld /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/Objects-normal/x86_64/VialerSIPLib_Example normal x86_64
    cd /Users/ash/Downloads/VialerSIPLib-develop/Example
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -L/Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Products/Debug-iphonesimulator -L/Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Products/Debug-iphonesimulator/CocoaLumberjack -L/Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Products/Debug-iphonesimulator/Reachability -L/Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Products/Debug-iphonesimulator/SPLumberjackLogFormatter -L/Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Products/Debug-iphonesimulator/VialerSIPLib -F/Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Products/Debug-iphonesimulator -F/Users/ash/Downloads/VialerSIPLib-develop/Example/Pods/Vialer-pjsip-iOS -filelist /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/Objects-normal/x86_64/VialerSIPLib_Example.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/Objects-normal/x86_64/VialerSIPLib_Example_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -fprofile-instr-generate -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/Objects-normal/x86_64/VialerSIPLib_Example.swiftmodule -ObjC -lCocoaLumberjack -lReachability -lSPLumberjackLogFormatter -lVialerSIPLib -lstdc++ -framework AVFoundation -framework AudioToolbox -framework CFNetwork -framework CoreMedia -framework SystemConfiguration -framework VialerPJSIP -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/VialerSIPLib_Example.app.xcent -weak_framework CallKit -framework CoreGraphics -framework UIKit -framework Foundation -lPods-VialerSIPLib_Example -Xlinker -dependency_info -Xlinker /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/Objects-normal/x86_64/VialerSIPLib_Example_dependency_info.dat -o /Users/ash/Library/Developer/Xcode/DerivedData/VialerSIPLib-dedkaxcrpfmvdsekftaazmcvfloc/Build/Intermediates.noindex/VialerSIPLib.build/Debug-iphonesimulator/VialerSIPLib_Example.build/Objects-normal/x86_64/VialerSIPLib_Example

ld: warning: ignoring file /Users/ash/Downloads/VialerSIPLib-develop/Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/ash/Downloads/VialerSIPLib-develop/Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP
Undefined symbols for architecture x86_64:
  "_pjsua_conf_remove_port", referenced from:
      -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
      -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
  "_pjmedia_tonegen_create2", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_enum_transports", referenced from:
      -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_set_snd_dev2", referenced from:
      -[VSLAudioController activateAudioSession] in libVialerSIPLib.a(VSLAudioController.o)
  "_pjsua_enum_codecs", referenced from:
      -[VSLEndpoint updateCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_codec_set_priority", referenced from:
      -[VSLEndpoint updateCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_add", referenced from:
      -[VSLAccount configureWithAccountConfiguration:error:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_destroy", referenced from:
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_get_info", referenced from:
      -[VSLCall initInboundCallWithCallId:account:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall connectDuration] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall calculateStats] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
      _onCallMediaState in libVialerSIPLib.a(VSLEndpoint.o)
      _onCallState in libVialerSIPLib.a(VSLEndpoint.o)
      ...
  "_pjsua_create", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_transport_get_info", referenced from:
      -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_logging_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjmedia_port_destroy", referenced from:
      -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_set_no_snd_dev", referenced from:
      -[VSLAudioController activateAudioSession] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLAudioController deactivateAudioSession] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_media_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_start", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_set_hold", referenced from:
      -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
  "_pj_thread_is_registered", referenced from:
      -[VSLAudioController checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLEndpoint createPJThreadAndPoolwithError:] in libVialerSIPLib.a(VSLEndpoint.o)
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_handle_ip_change", referenced from:
      -[VSLEndpoint ipAddressChanged:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_get_stream_info", referenced from:
      -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
  "_pjsua_call_get_stream_stat", referenced from:
      -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
  "_pj_str", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
      -[NSString(PJString) pjString] in libVialerSIPLib.a(NSString+PJString.o)
  "_pjsua_call_reinvite2", referenced from:
      -[VSLCall reinvite] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_dial_dtmf", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_acc_get_info", referenced from:
      -[VSLAccount registrationStatus] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount registrationExpiresTime] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount accountStateChanged] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_msg_data_init", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_hangup", referenced from:
      -[VSLCall hangup:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_transport_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_conf_connect", referenced from:
      -[VSLCall mediaStateChanged:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLRingback start] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_call_send_request", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_init", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_get_config", referenced from:
      -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_acc_del", referenced from:
      -[VSLAccount removeAccount] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_call_answer", referenced from:
      -[VSLCall setCallState:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall answerWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall decline:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_conf_disconnect", referenced from:
      -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_call_update2", referenced from:
      -[VSLCall update] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_conf_add_port", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_snd_dev_param_default", referenced from:
      -[VSLAudioController activateAudioSession] in libVialerSIPLib.a(VSLAudioController.o)
  "_pj_thread_register", referenced from:
      -[VSLAudioController checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLEndpoint createPJThreadAndPoolwithError:] in libVialerSIPLib.a(VSLEndpoint.o)
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_is_valid", referenced from:
      -[VSLAccount isAccountValid] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_call_xfer_replaces", referenced from:
      -[VSLCall transferToCall:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_ip_change_param_default", referenced from:
      -[VSLEndpoint ipAddressChanged:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_make_call", referenced from:
      -[VSLCall startWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
  "_pjmedia_tonegen_play", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_call_reinvite", referenced from:
      -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_transport_create", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_set_registration", referenced from:
      -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount unregisterAccount:] in libVialerSIPLib.a(VSLAccount.o)
  "_pj_pool_release", referenced from:
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_pool_create", referenced from:
      -[VSLEndpoint createPJThreadAndPoolwithError:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_config_default", referenced from:
      -[VSLAccount configureWithAccountConfiguration:error:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_call_setting_default", referenced from:
      -[VSLCall startWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall reinvite] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall update] in libVialerSIPLib.a(VSLCall.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kadze** [comment]
By the way. The size of new version of framework in my pods directory is only 5.6 MB. Old version weighted 108MB. Rather strange.

**Comment by redmerloen** [comment]
Did you run a `pod install` in the Example folder before building? 
Try cleaning the xcode project. I just tried it and everything works fine for the Example app.
Building en Running on my physical device.

**Comment by kadze** [comment]
Yes. I ran pod install. And I have done it once again after Your answer. I cloned repo again and in Example's folder ran "pod install". I still have the same result. 
I alse have read some details about "pod install" command here:   https://guides.cocoapods.org/using/pod-install-vs-update.html
Here we can see the text: "When you run pod install, it only resolves dependencies for pods that are not already listed in the Podfile.lock."
But git repo has the Podfile.lock   And there is - VialerSIPLib (3.0.0):   version. That is why you could see everything works on Your device. 
But I need updated pod. And if you run "pod update" instead of "pod install" you could see that actual version is VialerSIPLib (3.1.0).
Could you run "pod update" on your example project and try to build it?

**Comment by redmerloen** [comment]
I tried doing a `pod update` and still works building and compiling. On simulator (iPhone X) and also on my iPhone 6S.
Even when I delete my `Podfile.lock` and do a  `pod deintegrate` and try running and compiling on the same machine also works.
and when i do this on my file which 132MB according to my terminal there is the x86_64 architecture.
```
$ lipo -info Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Versions/A/VialerPJSIP
Architectures in the fat file: Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Versions/A/VialerPJSIP are: i386 armv7 armv7s arm64 x86_64
```
Not entirely sure what I can do for you.

**Comment by lexin** [comment]
The same issues on my side. Just downloaded the example. pod install was called. And here are the errors. 
https://www.dropbox.com/s/a512sd6kdawriie/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-03-05%2018.08.28.png?dl=0

**Comment by kadze** [comment]
I just have asked my colleague to run Example app. He has exactly the same result as I do. The same 53 linker errors on his machine.
![2018-03-05 18 08 28_preview](https://user-images.githubusercontent.com/6200265/36985863-136446aa-20a1-11e8-8eea-36ac23ac03cf.png)

**Comment by Beer-Koala** [comment]
I have same problem!
1. Downloaded zip, unpack
2. pod install in Example folder
3. copy Keys.swift.example and rename it to Keys.swift
4. i have problem when build!

PS developers, maybe can you try this algorithm on another mac?
![screenshot at mar 06 12-26-41](https://user-images.githubusercontent.com/24782246/37024358-a8bcf4ca-2139-11e8-95e5-7093e6edf010.png)

**Comment by redmerloen** [comment]
Could you try the newest version?

**Comment by Beer-Koala** [comment]
> Could you try the newest version?

Now I download newest version! And make the same steps. 
1. Downloaded zip, unpack
2. pod install in Example folder
3. copy Keys.swift.example and rename it to Keys.swift
And I have error again in second step.

![image](https://user-images.githubusercontent.com/24782246/37029195-93cc6fa6-2147-11e8-8d97-cbb784f4cce3.png)

**Comment by Beer-Koala** [comment]
now I make not "pod install" but "pod update". And step 2 done.

But after trying to build and have same errors like before...

![screenshot at mar 06 14-23-22](https://user-images.githubusercontent.com/24782246/37029887-f8513144-2149-11e8-900d-2fed3922798a.png)

**Comment by kadze** [comment]
I've just also tried the latest version. The same 53 linker errors. 
I've also found this page of vialerpjsip pod https://github.com/VoIPGRID/Vialer-pjsip-iOS . Does it mean that for Example project I need to additionally compile pjsip library myself?

**Comment by redmerloen** [comment]
@kadze No, you don't need to compile that your self. That is included in this library.
A pod install/update would be enough to get the newest version in the Example project.

**Comment by kadze** [comment]
Could you please explain for me the possible reasons why we have so different of library file size?

**Comment by redmerloen** [comment]
@kadze that file is being hosted with `git lfs` https://github.com/git-lfs/git-lfs/wiki/Installation 
Can you maybe try install that and see if the file is correct

**Comment by redmerloen** [comment]
@Beer-Koala Can you also check what the size is of the VialerPJSIP file in `Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Versions/a`?

**Comment by kadze** [comment]
I've just followed steps from your tutorial link
"Mac OSX
You may need to brew update to get all the new formulas
brew install git-lfs
git lfs install
"

Then I updated pods. The process was rather fast. Nothing look like downloading 100MB.
The size of Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Versions/A is still 134 bytes. Like I wrote in my pre-previous post. 
<img width="646" alt="screen shot 2018-03-06 at 2 30 34 pm" src="https://user-images.githubusercontent.com/6200265/37034621-90ed2e28-2152-11e8-9e02-f44a46daf263.png">

I have also downloaded the project from GitHub once again and installed pods one more time instead of just clean the project. Nothing changed.

**Comment by Beer-Koala** [comment]
@redmerloen folder A have size 5 MB, and file VialerPJSIP in this folder: 134 bytes.
This is after pod install\update.

**Comment by redmerloen** [comment]
I've update the project use a new version of the VialerPJSIP. Can you try updating with `pod update`/`pod install` and then try building the example app?

**Comment by kadze** [comment]
Thank you. 
I have figured out with my problem and fixed it. The problem was with cocoa pods cache. If you want to update large pods after the git-lfs installation you need to clean that cache. /Users/$USER/Library/Caches/CocoaPods

**Comment by redmerloen** [comment]
Good to here you fixed it!
Will add it to the readme

**Comment by TheEngineerz** [comment]
@kadze Kindly let me know exact procedure . because I have pod update/ pod install/ and pod cache clean --all

But still facing the same issue

**Comment by kadze** [comment]
As I said earlier, you should manually clean the cache directory with the path from my last post.

**Comment by lexin** [comment]
Mandatory step for me was the rebooting Mac OS after cleaning Cocoapods cache folder.

**Comment by NaiyerAghaz** [comment]
Hello to all I am getting same issue when download zip run example file, how I will fixed it.
![screen shot 2018-08-08 at 10 56 04 am](https://user-images.githubusercontent.com/12966229/43817920-b856f4dc-9af9-11e8-8baf-bf624b2103d3.png)

**Comment by redmerloen** [comment]
Issue is closed! Don't comment on closed issues, did you read the post to see what the fix is? And tried that?
