### ISSUE TITLE
Update library cause errors

### ISSUE THREAD

**Issue by SasanSoroush** [VoIPGRID/VialerSIPLib#159]
### Version

3.4.0

### File / Feature

VSLEndpoint.m

### Expected behavior

work properly

### Actual behavior

gives this error
VialerSIPLib/Pod/Classes/VSLEndpoint.m:445:22: No member named 'frm_ptime' in 'struct pjmedia_codec_opus_config'

### Other info

this works when I use the 3.1.3 version but when I update to 3.4.0 gives me this error

![screen shot 2018-10-21 at 12 49 31 pm](https://user-images.githubusercontent.com/31206210/47265149-40604e80-d530-11e8-8602-9d55646e8800.png)

**Comment by redmerloen** [comment]
Can you check if the linked library Vialer-pjsip-ios was also updated?
